- capitalname: "SEARCH ENGINE OPTIMISATION"
  icon: build
  linkname: Search Engine Optiomisation
  permalink: /services/search-engine-optimisation-seo-service-guide
  shortdes: TP Roofing installs new tiled roofs of any size or scope Sydney wide. Handpicked by Monier Roofing to join their elite team of Roofing specialists enables us to offer you Monier terracotta and concrete tiles at competitive prices...
    
- capitalname: "WEB DESIGN"
  icon: hammer
  linkname: Web Design
  permalink: /services/user-centric-and-content-first-web-design
  shortdes: TP Roofing are experts at sourcing and rectifying roof leaks. We prolong the life of your roof by providing roof maintenance services, fixing your leaking roof and delivering the best possible roofing solutions for your roofing needs...

- capitalname: "WEB DEVELOPMENT"
  icon: color-wand
  linkname: Web Devlopment
  permalink: /services/how-to-choose-the-right-web-developer
  shortdes: TP Roofing will replace your roof with the minimum of inconvenience, we excel at liaising with our clients and running our crews efficiently delivering a finished product that enhances your home and protects your most valuable asset...

- capitalname: "HOSTING AND MAINTENANCE"
  icon: build
  linkname: Website Hosting and Maintenance
  permalink: /services/website-hosting-and-maintenance-service
  shortdes: TP Roofing installs new tiled roofs of any size or scope Sydney wide. Handpicked by Monier Roofing to join their elite team of Roofing specialists enables us to offer you Monier terracotta and concrete tiles at competitive prices...
    


